'use strict';
const $=id=>document.getElementById(id), data=window.CLUB_DATA;
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const year=Number(today.slice(0,4));
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function empty(target,text){target.replaceChildren(el('div',text,'empty'));}
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}}
function imageURL(v){return typeof v==='string'&&((/^assets\/[\w./-]+$/.test(v)&&!v.includes('..'))||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v))?v:'';}
function link(title,url){const a=el('a',title);a.href=safeURL(url);a.target='_blank';a.rel='noopener noreferrer';return a;}
function record(r){const b=el('button',undefined,'record-card');b.type='button';b.append(el('span',r.group||r.category||r.role||r.year||r.date||'', 'tag'),el('h3',r.title||r.name),el('p',r.location||r.introduction||r.description||''));b.onclick=()=>{$('dialog-title').textContent=r.title||r.name;$('dialog-meta').textContent=[r.date,r.location,r.role].filter(Boolean).join(' · ');$('dialog-body').textContent=r.description||r.introduction||'추가 안내가 없습니다.';$('detail-dialog').showModal();};return b;}
function list(id,rows,message){const t=$(id);t.replaceChildren();if(!rows.length)empty(t,message);rows.forEach(r=>{t.append(record(r));if(r.url&&safeURL(r.url))t.append(link('공식 링크 ↗',r.url));});}
$('today-label').textContent=today+' · 한국시간';
list('members',data.members,'회원 소개 자료를 등록해 주세요.');list('history',data.history,'확인된 창립일과 연혁을 등록해 주세요.');list('businesses',data.businesses,'회원사 소개 자료를 등록해 주세요.');list('member-news',data.news,'등록된 경조사 소식이 없습니다.');list('clubs',data.clubs,'골프회·산악회 일정이 아직 등록되지 않았습니다.');list('district-news',data.district,'확인된 부산지구 동정은 공식 홈페이지에서 확인하세요.');
list('monthly-list',data.activities.filter(r=>r.date?.startsWith(today.slice(0,7))),'이달의 봉사 일정은 등록 준비 중입니다.');
const years=[...new Set([year,year-1,year-2,...data.activities.map(r=>Number(r.date?.slice(0,4))).filter(Number.isFinite)])].sort((a,b)=>b-a);years.forEach(y=>{const o=el('option',y+'년');o.value=y;$('year-select').append(o);});
function activities(){list('activity-list',data.activities.filter(r=>r.date?.startsWith($('year-select').value+'-')),'선택한 연도의 봉사 기록이 아직 없습니다.');} $('year-select').onchange=activities;activities();
const menu=document.querySelector('.menu-toggle');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);$('nav').classList.toggle('open',open);};
function closeMenu(){menu.setAttribute('aria-expanded','false');$('nav').classList.remove('open');}document.querySelectorAll('#nav a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});document.querySelector('.dialog-close').onclick=()=>$('detail-dialog').close();
$('scholar-form').onsubmit=e=>{e.preventDefault();window.open('https://scholar.google.com/scholar?q='+encodeURIComponent($('scholar-query').value),'_blank','noopener,noreferrer');};
data.youtube.filter(r=>safeURL(r.url)).forEach(r=>$('youtube-links').append(link(r.title,r.url)));if(!data.youtube.length)empty($('youtube-links'),'공식 채널 주소를 등록하면 여기에 연결됩니다.');
async function json(path){const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
json('data/news.json').then(d=>{const t=$('headlines');if(!d.items?.length){empty(t,'최신 기사를 아직 수집하지 못했습니다. 아래 원문 사이트에서 확인하세요.');return;}t.replaceChildren();d.items.slice(0,5).forEach(r=>{if(!safeURL(r.url))return;const box=el('div',undefined,'news-item');box.append(link(r.title,r.url),el('small',[r.source,r.published_at].filter(Boolean).join(' · ')));t.append(box);});$('news-updated').textContent='마지막 수집 '+new Date(d.updated_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' (한국시간)';}).catch(()=>empty($('headlines'),'뉴스 데이터가 없습니다. 원문 사이트에서 최신 기사를 확인하세요.'));
function svgNode(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function chart(target,rows,series,label){target.replaceChildren();if(!rows.length){empty(target,'출처가 있는 데이터가 등록되면 그래프를 표시합니다.');return;}const w=680,h=250,left=52,right=24,top=25,bottom=45;const vals=rows.flatMap(r=>series.map(s=>r[s.key])).filter(Number.isFinite);if(!vals.length){empty(target,'유효한 수치가 없습니다.');return;}let lo=Math.min(...vals),hi=Math.max(...vals);const pad=Math.max((hi-lo)*.15,1);lo-=pad;hi+=pad;const x=i=>left+i*(w-left-right)/Math.max(rows.length-1,1),y=v=>top+(hi-v)*(h-top-bottom)/(hi-lo);const svg=svgNode('svg',{viewBox:`0 0 ${w} ${h}`,class:'chart',role:'img','aria-label':label});svg.append(svgNode('title',{},label));for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg.append(svgNode('line',{x1:left,y1:y(v),x2:w-right,y2:y(v),stroke:'#dbe4ee'}),svgNode('text',{x:4,y:y(v)+4},v.toFixed(1)));}rows.forEach((r,i)=>{if(r.date===today)svg.append(svgNode('rect',{x:x(i)-14,y:top,width:28,height:h-top-bottom,fill:'#1261bf',opacity:'.08'}));if(rows.length<=12||i%Math.ceil(rows.length/10)===0)svg.append(svgNode('text',{x:x(i),y:h-14,'text-anchor':'middle',class:r.date===today?'today-text':''},r.date?.slice(5)||r.year));});series.forEach(s=>{svg.append(svgNode('polyline',{points:rows.map((r,i)=>`${x(i)},${y(r[s.key])}`).join(' '),fill:'none',stroke:s.color,'stroke-width':3}));rows.forEach((r,i)=>{const dot=svgNode('circle',{cx:x(i),cy:y(r[s.key]),r:4,fill:r.date===today?'#1261bf':s.color});dot.append(svgNode('title',{},`${r.date||r.year}: ${s.label} ${r[s.key]}`));svg.append(dot);});});target.append(svg);const legend=el('div',undefined,'chart-legend');series.forEach(s=>{const n=el('span',s.label);n.style.color=s.color;legend.append(n);});target.append(legend);}
function table(target,head,rows){target.replaceChildren();const t=el('table'),tr=el('tr');head.forEach(s=>tr.append(el('th',s)));const th=el('thead');th.append(tr);t.append(th);const body=el('tbody');rows.forEach(r=>{const tr=el('tr');if(r.today)tr.className='today';r.values.forEach(v=>{const td=el('td');if(v instanceof Node)td.append(v);else td.textContent=v;tr.append(td);});body.append(tr);});t.append(body);target.append(t);}
const cities={busan:{name:'부산',lat:35.1796,lon:129.0756},seoul:{name:'서울',lat:37.5665,lon:126.978},daegu:{name:'대구',lat:35.8714,lon:128.6014}};let city='busan',weatherCache=null,requestID=0;
const weatherCacheReady=json('data/weather.json').then(d=>{weatherCache=d;}).catch(()=>{});
function weatherRows(d){if(!d?.daily)return [];return d.daily.time.map((date,i)=>({date,min:d.daily.temperature_2m_min[i],max:d.daily.temperature_2m_max[i]})).filter(r=>Number.isFinite(r.min)&&Number.isFinite(r.max));}
function showWeather(rows,cached){chart($('weather-chart'),rows,[{key:'max',label:'최고기온 (°C)',color:'#bd692a'},{key:'min',label:'최저기온 (°C)',color:'#526f8d'}],cities[city].name+' 날짜별 최저·최고기온');table($('weather-table'),['날짜','최저 °C','최고 °C'],rows.map(r=>({today:r.date===today,values:[r.date+(r.date===today?' · 오늘':''),r.min,r.max]})));$('weather-summary').replaceChildren();$('weather-summary').className='weather-summary';const yesterday=new Date(today+'T00:00:00Z');yesterday.setUTCDate(yesterday.getUTCDate()-1);for(const [date,name] of [[yesterday.toISOString().slice(0,10),'어제'],[today,'오늘']]){const row=rows.find(r=>r.date===date),box=el('div',undefined,date===today?'today':'');box.append(el('span',name+' · '+date),el('strong',row?`${row.min}° / ${row.max}°`:'선택 기간의 자료 없음'));$('weather-summary').append(box);}$('weather-status').textContent=rows.length?`${cities[city].name} · ${rows.length}일 ${cached?'저장 자료':'조회 자료'}${cached?' · 수집 '+weatherCache.updated_at:''}`:'해당 기간에 사용할 수 있는 자료가 없습니다.';}
async function loadWeather(){const id=++requestID,start=$('weather-start').value,end=$('weather-end').value;if(!start||!end||start>end||((Date.parse(end)-Date.parse(start))/86400000)>31){$('weather-status').textContent='시작·종료 날짜를 확인해 주세요. 최대 32일을 조회할 수 있습니다.';return;}const c=cities[city];$('weather-status').textContent=c.name+' 날씨를 조회합니다…';$('weather-refresh').disabled=true;const cutoff=new Date(today+'T00:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-5);const archive=end<cutoff.toISOString().slice(0,10);const url=new URL(archive?'https://archive-api.open-meteo.com/v1/archive':'https://api.open-meteo.com/v1/forecast');Object.entries({latitude:c.lat,longitude:c.lon,daily:'temperature_2m_max,temperature_2m_min',timezone:'Asia/Seoul',start_date:start,end_date:end}).forEach(([k,v])=>url.searchParams.set(k,v));try{const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const d=await r.json();if(id!==requestID)return;showWeather(weatherRows(d),false);}catch{if(id!==requestID)return;await weatherCacheReady;if(id!==requestID)return;const rows=weatherRows(weatherCache?.cities?.[city]).filter(r=>r.date>=start&&r.date<=end);if(rows.length)showWeather(rows,true);else{$('weather-summary').replaceChildren();$('weather-table').replaceChildren();empty($('weather-chart'),'날씨 자료를 가져오지 못했습니다. 연결을 확인한 뒤 다시 조회하세요.');$('weather-status').textContent='조회 실패 · 실제 기온 자료가 없어 그래프를 표시하지 않습니다.';}}finally{if(id===requestID)$('weather-refresh').disabled=false;}}
document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{city=b.dataset.city;document.querySelectorAll('[data-city]').forEach(x=>x.setAttribute('aria-pressed',x===b));loadWeather();});$('weather-refresh').onclick=loadWeather;loadWeather();
const metrics={budget:{title:'최근 10년 복지예산 추이',description:'공식 자료의 연도별 복지예산. 본예산·추경·결산과 부처 예산·총지출은 구분하여 같은 기준으로 입력하세요.',sources:[['기획재정부','https://www.moef.go.kr/'],['보건복지부','https://www.mohw.go.kr/']]},recipients:{title:'복지수급자 추이',description:'수급 대상과 집계 기준일이 동일한 통계를 비교하세요. 서로 다른 제도의 수급자는 중복될 수 있습니다.',sources:[['KOSIS 국가통계포털','https://kosis.kr/'],['보건복지부','https://www.mohw.go.kr/']]},regional:{title:'지역별 복지 현황',description:'지역을 선택하여 연도별 통계를 확인하세요. 지역 인구 규모와 지표 정의를 함께 확인하세요.',sources:[['지방재정365','https://www.lofin365.go.kr/'],['KOSIS','https://kosis.kr/']]},volunteering1365:{title:'1365 자원봉사 통계',description:'1365의 등록인원·실인원·연인원·시간을 구분해 단일 지표로 입력하세요.',sources:[['1365 자원봉사포털','https://www.1365.go.kr/']]},volunteeringVms:{title:'VMS 사회복지 자원봉사 통계',description:'VMS 집계의 봉사자 수·활동 횟수·봉사시간 중 동일한 지표를 비교하세요. 1365와 단순 합산하지 마세요.',sources:[['VMS','https://www.vms.or.kr/']]}};let metric='budget',stats=[];
function csvParse(text){const rows=[];let row=[],v='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(v);v='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v='';}else v+=c;}if(quoted)throw Error('CSV 따옴표가 닫히지 않았습니다.');row.push(v);if(row.some(x=>x.trim()))rows.push(row);const header=rows.shift()?.map(x=>x.trim().replace(/^\uFEFF/,''))||[];const required=['metric','year','region','value','unit','source_name','source_url'];if(required.some(k=>!header.includes(k)))throw Error('CSV 열 이름이 양식과 다릅니다.');return rows.map((r,i)=>{const o=Object.fromEntries(header.map((k,j)=>[k,(r[j]||'').trim()]));if(!metrics[o.metric]||!/^\d{4}$/.test(o.year)||!o.region||o.value===''||!Number.isFinite(Number(o.value))||!o.unit||!o.source_name||!safeURL(o.source_url))throw Error(`${i+2}행: 지표·연도·지역·수치·단위·HTTPS 출처를 확인하세요.`);o.year=Number(o.year);o.value=Number(o.value);return o;});}
function regions(){const s=$('region-select'),previous=s.value;s.replaceChildren();const rs=[...new Set(stats.filter(r=>r.metric===metric).map(r=>r.region))];(rs.length?rs:['전국']).forEach(r=>{const o=el('option',r);o.value=r;s.append(o);});if(rs.includes(previous))s.value=previous;renderMetric();}
function renderMetric(){const m=metrics[metric];$('metric-title').textContent=m.title;$('metric-description').textContent=m.description;const all=stats.filter(r=>r.metric===metric&&r.region===$('region-select').value).sort((a,b)=>a.year-b.year);const latest=all.at(-1)?.year;const rows=all.filter(r=>r.year>=latest-9);const units=[...new Set(rows.map(r=>r.unit))];const keys=new Set(rows.map(r=>r.year));const conflict=units.length>1||keys.size!==rows.length;$('metric-status').textContent=conflict?'단위가 섞이거나 같은 연도 자료가 중복되어 그래프를 표시하지 않습니다. 입력 자료를 확인하세요.':rows.length?`${rows.length}개 연도 · ${units[0]} · 확보된 최신 연도 기준 10년 범위`:'공식 수치 미등록 · 임의 수치 없이 출처만 안내합니다.';chart($('metric-chart'),conflict?[]:rows,[{key:'value',label:units[0]||'수치',color:'#1f5582'}],m.title);table($('metric-table'),['연도','지역','수치','단위','출처'],rows.map(r=>({values:[r.year,r.region,r.value.toLocaleString('ko-KR'),r.unit,link(r.source_name,r.source_url)]})));$('metric-sources').replaceChildren(...m.sources.map(s=>link(s[0]+' ↗',s[1])));}
Object.entries(metrics).forEach(([key,m])=>{const b=el('button',m.title);b.setAttribute('aria-pressed',key===metric);b.onclick=()=>{metric=key;document.querySelectorAll('#metric-tabs button').forEach(x=>x.setAttribute('aria-pressed',x===b));regions();};$('metric-tabs').append(b);});$('region-select').onchange=renderMetric;regions();fetch('data/statistics.csv').then(r=>{if(!r.ok)throw Error();return r.text();}).then(t=>{stats=csvParse(t);regions();}).catch(()=>{});$('csv-file').onchange=async()=>{try{const file=$('csv-file').files[0];if(!file)return;stats=csvParse(await file.text());regions();$('import-status').textContent=`${stats.length}행을 미리 보기에 불러왔습니다. GitHub에는 아직 반영되지 않았습니다.`;}catch(e){$('import-status').textContent=e.message;}};
let publicPhotos=[],localPhotos=null,photoDB;
function db(){if(photoDB)return photoDB;photoDB=new Promise((resolve,reject)=>{const r=indexedDB.open('busan-hanil-photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('album');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return photoDB;}
async function readAlbum(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('album').objectStore('album').get('photos');r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error);});}
async function saveAlbum(rows){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('album','readwrite');tx.objectStore('album').put(rows,'photos');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
function renderPhotos(){const rows=localPhotos??publicPhotos,t=$('gallery');t.replaceChildren();if(!rows.length){const f=el('figure'),i=el('img');i.src='assets/busan.png';i.alt='부산 광안대교 풍경';f.append(i,el('figcaption','부산 광안대교 · 클럽 행사사진은 등록 준비 중'));t.append(f);return;}rows.forEach((r,index)=>{const src=imageURL(r.image);if(!src)return;const f=el('figure'),i=el('img');i.src=src;i.alt=r.title||'행사사진';i.loading='lazy';f.append(i,el('figcaption',[r.date,r.title].filter(Boolean).join(' · ')));const remove=el('button','사진 삭제');remove.onclick=async()=>{const next=[...(localPhotos??publicPhotos)];next.splice(index,1);try{await saveAlbum(next);localPhotos=next;renderPhotos();$('photo-status').textContent='이 브라우저에서 삭제했습니다. 공개 반영은 업데이트 파일을 내려받아 교체하세요.';}catch{$('photo-status').textContent='브라우저 저장에 실패했습니다.';}};f.append(remove);t.append(f);});}
(async()=>{try{const d=await json('data/gallery.json');publicPhotos=Array.isArray(d.photos)?d.photos:[];}catch{}publicPhotos=[...data.photos,...publicPhotos];try{localPhotos=await readAlbum();}catch{}renderPhotos();})();
function readImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
$('photo-files').onchange=async()=>{try{const files=[...$('photo-files').files];if(!files.length)return;const rows=[...(localPhotos??publicPhotos)];if(rows.length+files.length>30)throw Error('한 앨범에는 최대 30장의 사진을 등록할 수 있습니다.');if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024))throw Error('사진은 PNG/JPEG/WebP, 파일당 10MB 이하로 선택하세요.');const added=await Promise.all(files.map(async f=>({title:$('photo-title').value.trim()||f.name,date:$('photo-date').value,image:await readImage(f)})));rows.push(...added);await saveAlbum(rows);localPhotos=rows;renderPhotos();$('photo-status').textContent=`${added.length}장을 이 브라우저에 저장했습니다. 공개하려면 업데이트 파일을 GitHub에 올리세요.`;}catch(e){$('photo-status').textContent=e.message;}finally{$('photo-files').value='';}};
$('photo-export').onclick=()=>{const rows=localPhotos??publicPhotos;const url=URL.createObjectURL(new Blob([JSON.stringify({photos:rows},null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='gallery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('photo-status').textContent='다운로드한 gallery.json으로 GitHub의 data/gallery.json을 교체하세요. 공개 동의가 있는 사진만 올리세요.';};
$('photo-reset').onclick=async()=>{try{const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('album','readwrite');tx.objectStore('album').delete('photos');tx.oncomplete=resolve;tx.onerror=reject;});localPhotos=null;renderPhotos();$('photo-status').textContent='브라우저 편집을 초기화했습니다. 공개 앨범은 유지됩니다.';}catch{$('photo-status').textContent='초기화에 실패했습니다.';}};
